version: '2'
services:
  jhipster_demo-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jhipster_demo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipster_demo
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
